### ISSUE TITLE
src/vertex_triangle_adjacency.cpp used in both computing per vertex normals and per corner normals

### ISSUE THREAD

**Issue by velociraptor111** [alecjacobson/computer-graphics-meshes#1]
From my understanding in computing both per vertex normals and per corner normals, we need to be able to get all the Faces which are incident on the vertex. 

Is there any particular reason why the function vertex_triangle_adjacency() is only included in the per_corner_normals.cpp and not in per_vertex_normals.cpp ??

**EDIT**
I ended up just importing the function in my per_vertex_normals.cpp , just verifying that we are allowed to do this

**Comment by velociraptor111** [comment]
Also, the math equations in the README is very difficult to read, I think Github is not properly converting the syntax to a readable format... How do we get the equations to be in a readable format?

**Comment by alecjacobson** [comment]
yes, this is OK. Though you could ask yourself if it's necessary.
