### ISSUE TITLE
Extension for A5

### ISSUE THREAD

**Issue by ZhuaMei** [alecjacobson/computer-graphics-meshes#12]
I know some of the students have tests for CSC373 and CSC411 on Fridays, and I know that we asked for an extension for a4 last week already, while an extension for A5 would be such a relief for us to spend enough time to work on the assignment and preparing for the test. Since the assignment this time requires caution and  100% concentration (maybe it's just for me not to mess up the index and mapping, which causes me a lot of troubles), I would really appropriate an extension, even for one day.

**Comment by Ian729** [comment]
I agree.
And since A6 is not due next week, I don't think this extension(if possible) will affect the next assignment.

**Comment by alecjacobson** [comment]
Please do not post administrative questions on GitHub. These belong on the discussion board for this session.
