### ISSUE TITLE
easy way to compare a row of matrix with vector3d? / easy way to assign a vector3d to a row of matrix?

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-meshes#13]
Hi, is there any one-liner to compare a row of matrix (col # is 3) with a vector 3d . Also, is there any easy way to assign the vector3d to one row of matrix with 3 col? Now I can only assign each value one by one and is very time consuming. I checked the api page for eigen but nothing seems very helpful

**Comment by bryantam** [comment]
For assigning a RowVector3d to one row of matrix, you can do `matrix.row(i) = vector`.
Not sure what you mean by comparing a row with a matrix. `matrix.row(i)` would return a RowVector, and you can do whatever you can do with a vector

**Comment by RioAraki** [comment]
Thanks for your answer, that really helps! also may I ask do you know how to print vector for debugging in one line?

**Comment by bryantam** [comment]
I have found something called IOFormat: https://stackoverflow.com/questions/24876570/how-to-print-eigen-variables-in-columns
But I haven't used that before. I found doing `std::cout << v.x() << v.y() << v.z()` easier.

**Comment by RioAraki** [comment]
thanks you, appreciated!
