### ISSUE TITLE
About latitude longitude Mercator parameterization

### ISSUE THREAD

**Issue by Xeroken** [alecjacobson/computer-graphics-meshes#15]
It says to use that for sphere, but I can't find anything about it in the textbook or instructions. Can someone give me an explanation of what it is?

**Comment by Xeroken** [comment]
Just things about Mercator projection but I'm not sure about what the derivation in this means:
https://en.wikipedia.org/wiki/Mercator_projection#Derivation_of_the_Mercator_projection

**Comment by RioAraki** [comment]
https://www.youtube.com/watch?v=hUH-ipgqOjs This video is so useful and i would recommand to everyone who is struggling on Mercator projection
