### ISSUE TITLE
readOBJ Warnings: UV and UF

### ISSUE THREAD

**Issue by MathieuTuli** [alecjacobson/computer-graphics-meshes#22]
`write_obj.cpp` requires us to write the UV and UF values into the `.obj` file, however, when running `./obj`, libigl returns the warnings saying that it chose to ignore the lines representing the UV and UF values. My understanding was that UV and UF are the coords/indices to represent the 2D parameterization, which I have seen described as being the `vp` and `curv2` values. I noticed that in `obj.cpp`, UV and UF are passed as the texture coordinates, so should we be treating them as that in our `write_obj.cpp`?

**Comment by abhimadan** [comment]
The texture coordinates are a 2D parameterization of the surface — you're using the mapping from a 3D point to a 2D point to figure out which part of the texture image should be applied to the corresponding surface point. Use the `vt` attribute for `UV` data, and include `UF` in the `f` entries.

**Comment by MathieuTuli** [comment]
That makes sense. Thanks.
