### ISSUE TITLE
Different threshold in images in README

### ISSUE THREAD

**Issue by MathieuTuli** [alecjacobson/computer-graphics-meshes#23]
I just wanted to confirm whether the `fandisk` images in the README used a different degree threshold or not. 
![DeepinScreenshot_select-area_20191021192750](https://user-images.githubusercontent.com/20361597/67250927-4f2b5b00-f43b-11e9-9f15-cd4a745101d2.png)

The reason I ask is if you look at the image above (a per corner normal image), on the left side there is a smooth curve transition rather than sharp as in the readme images, and for the life of me I can't figure out why this corner case occurs

**Comment by abhimadan** [comment]
It doesn't use a different threshold, though remember that the threshold is in degrees, not radians.

**Comment by MathieuTuli** [comment]
I do the proper degree to radian conversion, and it's only that left side curve that doesn't match up for some reason.

**Comment by abhimadan** [comment]
Then it's probably not your degree threshold. Try stepping through your code with a debugger to look at the calculation of some of those corner normals (you can set a conditional breakpoint so you don't have to spend all day skipping irrelevant breakpoint hits).

**Comment by MathieuTuli** [comment]
I'll give that a try for sure. I did try an alternative radian to degree conversion, and wanted to share those results one last time.
![DeepinScreenshot_select-area_20191021200317](https://user-images.githubusercontent.com/20361597/67251760-222c7780-f43e-11e9-8797-3b7a541371fb.png)
![DeepinScreenshot_select-area_20191021200339](https://user-images.githubusercontent.com/20361597/67251761-222c7780-f43e-11e9-8087-7e4a42483d91.png)

As you can see in the first image, I can achieve that sharp edge, but in the second, there is faceting when I believe we should get smooth. Or is this as expected ?

**Comment by abhimadan** [comment]
There's a fairly small angle difference between faces in that region, so it's close to the provided threshold. You can expect a somewhat faceted appearance there.

**Comment by MathieuTuli** [comment]
sounds good, thanks for the help.
