### ISSUE TITLE
per-vertex-normals header instruction mistake?

### ISSUE THREAD

**Issue by WilliamSati** [alecjacobson/computer-graphics-meshes#28]
Hello, I think there is a mistake regarding the instructions in the header per-vertex-normals.h. It says that the output should return a "#V by 3 list of per-face unit normal vectors" when, from my understanding, it should be returning something more similar to the per-corner-normals function, which is a "#F*3 by 3 list of mesh vertex 3D normals". Is this correct?

**Comment by ZewenShen** [comment]
No, the documentation is correct. This is because each vertex only has one possible normal direction in the per-vertex scenario. Therefore, for simplicity, people usually store them in the form of a #V by 3 matrix. That also explains the name "per-vertex".

**Comment by WilliamSati** [comment]
oh I see. I think 'per-face' is the wrong word then right? It should say #V by 3 list of _per-vertex_ unit normal vectors. Also if I understand correctly then the per-vertex version should also include the vertex_triangle_adjacency.h as a hint right?

**Comment by ZewenShen** [comment]
I agree. It sounds like one should assign one normal to each face, while it's not true in practice. 

"It should say #V by 3 list of per-vertex unit normal vectors." I don't quite understand this. The per-face normal should of size #row of F by 3.

You are free to use vertex_triangle_adjacency and it could work, although it's not a must.
