### ISSUE TITLE
Warnings on build

### ISSUE THREAD

**Issue by dakmcinnis** [alecjacobson/computer-graphics-meshes#29]
**Environment:**
Device: MacBook Pro (Mid 2015)
OS: macOS Big Sur Version 11.5.2
Processor: 2.2 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris PRo 1536 MB

**Build script:**

> cmake -DCMAKE_BUILD_TYPE=Debug ..

OR

> cmake ../ -DCMAKE_BUILD_TYPE=Release

**Warnings:**
<img width="1318" alt="Screen Shot 2022-02-14 at 3 16 20 PM" src="https://user-images.githubusercontent.com/54950797/153939930-d6af1fb4-bd53-4abd-8e07-552fe3fcaf50.png">

**Comment by abhimadan** [comment]
Don't worry about these warnings, they don't cause any problems in practice.
