### ISSUE TITLE
Assertion in igl::readOBJ

### ISSUE THREAD

**Issue by ChrisVinhNguyen** [alecjacobson/computer-graphics-meshes#3]
When I try to run .obj, I get the following assertion, which seems to come from igl::readOBJ:

```
obj: /nfs/ug/homes-1/n/nguy1109/CSC418-asst5/libigl/external/eigen/Eigen/src/Core/DenseCoeffsBase.h:114: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::DenseCoeffsBase<Derived, 0>::Index, Eigen::DenseCoeffsBase<Derived, 0>::Index) const [with Derived = Eigen::Matrix<int, -1, -1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const int&; Eigen::DenseCoeffsBase<Derived, 0>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
Abort

```
This appears to happen when the obj file called contains face data (ie. f v1 v2 v3 v4), as removing these lines from the obj file does not result in an assertion.

I have even tried calling igl::readOBJ on an standard obj file that I downloaded online, which had the same results as using the obj file I generated.

**Comment by velociraptor111** [comment]
Works for me , can you also post maybe a snippet of code/obj file on what you are trying to achieve?

**Comment by ChrisVinhNguyen** [comment]
I think I resolved the issue, it seems like I was incorrectly setting the UF/NF vectors
