### ISSUE TITLE
obj.cpp has no return value

### ISSUE THREAD

**Issue by dakmcinnis** [alecjacobson/computer-graphics-meshes#30]
**Question:** Should the starter code for `obj.cpp` be changed?

**Context:** 

I was trying to debug a runtime error. Since the error wasn't very informative, I was recommended to rename the function in `obj.cpp` from `main` to `main1`. I made the following changes:

<img width="294" alt="Screen Shot 2022-02-14 at 9 06 14 PM" src="https://user-images.githubusercontent.com/54950797/153979012-cc9b8c92-cab3-475f-b354-58115dc5abc8.png">
<img width="283" alt="Screen Shot 2022-02-14 at 9 06 19 PM" src="https://user-images.githubusercontent.com/54950797/153979013-55963e6f-097d-40b4-9d81-9b4e43c971f1.png">

**Problem:**

With the changes shown above, I get the following compile time warning:

<img width="765" alt="Screen Shot 2022-02-14 at 9 08 38 PM" src="https://user-images.githubusercontent.com/54950797/153979084-3bd1038e-4788-429b-ba14-54b486d52958.png">

**Comment by ZewenShen** [comment]
Yes. There should be a 'return 0' at the end of obj.cpp. But usually, compilers will handle that well, and you don't need to worry about that warning.
