### ISSUE TITLE
Help debugging write_obj.cpp & cube.cpp

### ISSUE THREAD

**Issue by dakmcinnis** [alecjacobson/computer-graphics-meshes#31]
**Problem:** 

I'm having a runtime error from an assertion. I cannot find the assertion in our starter code, nor in libigl. Does anyone know where this assertion is and/or what I'm doing wrong?

**My approach:**

1. First, I commented out the sphere code from `obj.cpp` and implementing `cube.cpp`. This built without warnings/errors.
2. Next, I implemented just "v", "vt" and "vn" for write_obj.cpp. This built and ran as expected.
3. Finally, when I added the implementation for "f" for write_obj.cpp, I got this runtime error:

<img width="1047" alt="Screen Shot 2022-02-14 at 9 20 31 PM" src="https://user-images.githubusercontent.com/54950797/153980257-d8e77a35-d388-4875-8d21-44c6da996fca.png">

**Comment by dakmcinnis** [comment]
Using `thread backtrace`, it appears that v.set_mesh() has the assert:

<img width="1850" alt="Screen Shot 2022-02-14 at 9 32 01 PM" src="https://user-images.githubusercontent.com/54950797/153981505-948a59e5-9ee0-4445-933b-d22034dab59f.png">
<img width="741" alt="Screen Shot 2022-02-14 at 9 32 34 PM" src="https://user-images.githubusercontent.com/54950797/153981506-34a66a5f-d78b-4c14-bc83-be56794a1f21.png">

**Comment by dakotamcinnis** [comment]
Could it be a result of bad values in `cube.cpp`? I implemented this assuming the coordinates are x,y,z, however it sounds like it's y,z,x

**Comment by abhimadan** [comment]
You should check in your debugger, but I'm pretty sure it's because you didn't fill in the F matrices (particularly UF and NF). The mesh viewing function assumes those are filled and eigen complains because your index is out of range. Getting the vertex coordinate positions mixed up will just make it look incorrect, but won't cause a segfault or assertion error - that's pretty much always from indexing.

**Comment by dakmcinnis** [comment]
Thanks! It was an index out of range problem. Solution was handling this in write_obj.cpp:
> "Warning: In C++ indices "start" at 0, but in a .obj file the first element in a list has index 1."
